SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
CREATE TABLE `motivo` (
  `ID` int(11) NOT NULL,
  `MOTIVO` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `pais` (
  `ID` int(3) NOT NULL,
  `NOMBRE` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `persona` (
  `ID` int(11) NOT NULL,
  `NOMBRE` varchar(45) NOT NULL,
  `APELLIDO` varchar(45) NOT NULL,
  `FECHA_NACIMIENTO` date NOT NULL,
  `FECHA_ENTRADA` date NOT NULL,
  `FECHA_SALIDA` date DEFAULT NULL,
  `MOTIVO` int(20) NOT NULL,
  `PAIS` int(3) NOT NULL,
  `PAIS_ENTRADA` int(3) NOT NULL,
  `PAIS_SALIDA` int(3) NOT NULL,
  `DNI` int(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
ALTER TABLE `motivo`
  ADD PRIMARY KEY (`ID`);
ALTER TABLE `pais`
  ADD PRIMARY KEY (`ID`);
ALTER TABLE `persona`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `PAIS` (`PAIS`) USING BTREE,
  ADD KEY `PAIS_ENTRADA` (`PAIS_ENTRADA`) USING BTREE,
  ADD KEY `PAIS_SALIDA` (`PAIS_SALIDA`),
  ADD KEY `MOTIVO` (`MOTIVO`);
ALTER TABLE `motivo`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `pais`
  MODIFY `ID` int(3) NOT NULL AUTO_INCREMENT;
ALTER TABLE `persona`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `persona`
  ADD CONSTRAINT `persona_ibfk_1` FOREIGN KEY (`PAIS`) REFERENCES `pais` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE,
  ADD CONSTRAINT `persona_ibfk_2` FOREIGN KEY (`PAIS_ENTRADA`) REFERENCES `pais` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE,
  ADD CONSTRAINT `persona_ibfk_3` FOREIGN KEY (`PAIS_SALIDA`) REFERENCES `pais` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE,
  ADD CONSTRAINT `persona_ibfk_4` FOREIGN KEY (`MOTIVO`) REFERENCES `motivo` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
COMMIT;
